UPDATE game_event SET description = '仲夏火焰节' WHERE description = 'Midsummer Fire Festival';
UPDATE game_event SET description = '冬幕节' WHERE description = 'Winter Veil';
UPDATE game_event SET description = '暗月马戏团（泰罗卡森林）' WHERE description = 'Darkmoon Faire (Terokkar Forest)';
UPDATE game_event SET description = '暗月马戏团（艾尔文森林）' WHERE description = 'Darkmoon Faire (Elwynn Forest)';
UPDATE game_event SET description = '暗月马戏团（莫高雷）' WHERE description = 'Darkmoon Faire (Mulgore)';
UPDATE game_event SET description = '春节' WHERE description = 'New Year\'s Eve';
UPDATE game_event SET description = '新年' WHERE description = 'Lunar Festival';
UPDATE game_event SET description = '情人节' WHERE description = 'Love is in the Air';
UPDATE game_event SET description = '复活节' WHERE description = 'Noblegarden';
UPDATE game_event SET description = '儿童周' WHERE description = 'Children\'s Week';
UPDATE game_event SET description = '收获节' WHERE description = 'Harvest Festival';
UPDATE game_event SET description = '万圣节' WHERE description = 'Hallow\'s End';
UPDATE game_event SET description = '元素入侵' WHERE description = 'Elemental Invasions';
UPDATE game_event SET description = '荆棘谷钓鱼大赛' WHERE description = 'Stranglethorn Fishing Extravaganza Announce';
UPDATE game_event SET description = '荆棘谷钓鱼大赛' WHERE description = 'Stranglethorn Fishing Extravaganza Fishing Pools';
UPDATE game_event SET description = '古拉巴什竞技场' WHERE description = 'Gurubashi Arena Booty Run';
UPDATE game_event SET description = '天灾入侵' WHERE description = 'Scourge Invasion';
UPDATE game_event SET description = '战斗的召唤：奥特兰克山谷！' WHERE description = 'Call to Arms: Alterac Valley!';
UPDATE game_event SET description = '战斗的召唤：战歌峡谷！' WHERE description = 'Call to Arms: Warsong Gulch!';
UPDATE game_event SET description = '战斗的召唤：阿拉希盆地！' WHERE description = 'Call to Arms: Arathi Basin!';
UPDATE game_event SET description = '战斗的召唤：风暴之眼！' WHERE description = 'Call to Arms: Eye of the Storm!';
UPDATE game_event SET description = '甲虫的召唤' WHERE description = 'AQ War Effort';
UPDATE game_event SET description = '暗月马戏团重建（艾尔文森林）' WHERE description = 'Darkmoon Faire Building (Elwynn Forest)';
UPDATE game_event SET description = '美酒节' WHERE description = 'Brewfest';
UPDATE game_event SET description = '狂欢节' WHERE description = 'Nights';
UPDATE game_event SET description = '感恩节' WHERE description = 'Pilgrim\'s Bounty';
UPDATE game_event SET description = '疯狂之缘，格里雷克' WHERE description = 'Edge of Madness, Gri\'lek';
UPDATE game_event SET description = '疯狂之缘，哈扎拉尔' WHERE description = 'Edge of Madness, Hazza\'rah';
UPDATE game_event SET description = '疯狂之缘，雷纳塔基' WHERE description = 'Edge of Madness, Renataki';
UPDATE game_event SET description = '疯狂之缘，乌苏雷' WHERE description = 'Edge of Madness, Wushoolay';
UPDATE game_event SET description = '竞技场锦标赛' WHERE description = 'Arena Tournament';
UPDATE game_event SET description = '牛头人酋长音乐会' WHERE description = 'L70ETC Concert';
UPDATE game_event SET description = '达拉然：米尼格布' WHERE description = 'Dalaran: Minigob';
UPDATE game_event SET description = '本月美酒：十二月' WHERE description = 'Brew of the Month October';
UPDATE game_event SET description = '本月美酒：十一月' WHERE description = 'Brew of the Month November';
UPDATE game_event SET description = '本月美酒：十月' WHERE description = 'Brew of the Month December';
UPDATE game_event SET description = '本月美酒：九月' WHERE description = 'Brew of the Month January';
UPDATE game_event SET description = '本月美酒：八月' WHERE description = 'Brew of the Month February';
UPDATE game_event SET description = '本月美酒：七月' WHERE description = 'Brew of the Month March';
UPDATE game_event SET description = '本月美酒：六月' WHERE description = 'Brew of the Month April';
UPDATE game_event SET description = '本月美酒：五月' WHERE description = 'Brew of the Month May';
UPDATE game_event SET description = '本月美酒：四月' WHERE description = 'Brew of the Month June';
UPDATE game_event SET description = '本月美酒：三月' WHERE description = 'Brew of the Month July';
UPDATE game_event SET description = '本月美酒：二月' WHERE description = 'Brew of the Month August';
UPDATE game_event SET description = '本月美酒：一月' WHERE description = 'Brew of the Month September';
UPDATE game_event SET description = '冬拥湖联盟防御战' WHERE description = 'Wintergrasp Alliance Defence';
UPDATE game_event SET description = '冬拥湖部落防御战' WHERE description = 'Wintergrasp Horde Defence';
UPDATE game_event SET description = '亡灵节' WHERE description = 'Pirates\' Day';
UPDATE game_event SET description = '亡灵节' WHERE description = 'Day of the Dead';
UPDATE game_event SET description = '冬幕节：礼物' WHERE description = 'Winter Veil: Gifts';
UPDATE game_event SET description = '战斗的召唤：寇魔古寺！' WHERE description = 'Call to Arms: Strand of the Ancients!';
UPDATE game_event SET description = '战斗的召唤：征服之岛！' WHERE description = 'Call to Arms: Isle of Conquest!';
UPDATE game_event SET description = '竞技场第三季' WHERE description = 'Arena Season 3';
UPDATE game_event SET description = '竞技场第四季' WHERE description = 'Arena Season 4';
UPDATE game_event SET description = '竞技场第五季' WHERE description = 'Arena Season 5';
UPDATE game_event SET description = '竞技场第六季' WHERE description = 'Arena Season 6';
UPDATE game_event SET description = '竞技场第七季' WHERE description = 'Arena Season 7';
UPDATE game_event SET description = '竞技场第八季' WHERE description = 'Arena Season 8';
UPDATE game_event SET description = '扎拉赞恩的灭亡' WHERE description = 'Zalazane\'s Fall';
UPDATE game_event SET description = '荆棘谷钓鱼大赛' WHERE description = 'Stranglethorn Fishing Extravaganza Turn-ins';
UPDATE game_event SET description = '卡鲁亚克钓鱼大赛' WHERE description = 'Kalu\'ak Fishing Derby Turn-ins';
UPDATE game_event SET description = '卡鲁亚克钓鱼大赛' WHERE description = 'Kalu\'ak Fishing Derby Fishing Pools';
UPDATE game_event SET description = '派瑞 加奈尔' WHERE description = 'Perry Gatner';
UPDATE game_event SET description = 'AT事件触发（提里奥的演说）' WHERE description = 'AT Event Trigger (Tirion Speech)';
UPDATE game_event SET description = 'AT事件触发（部落）' WHERE description = 'AT Event Trigger (Horde Event)';
UPDATE game_event SET description = 'AT事件触发（联盟）' WHERE description = 'AT Event Trigger (Alliance Event)';
UPDATE game_event SET description = '美酒节重建（铁炉堡）' WHERE description = 'Brewfest Building (Iron Forge)';
UPDATE game_event SET description = '暗月马戏团重建（莫高雷）' WHERE description = 'Darkmoon Faire Building (Mulgore)';
UPDATE game_event SET description = '烟花庆典' WHERE description = 'Fireworks Spectacular';
UPDATE game_event SET description = '时钟' WHERE description = 'Hourly Bells';
